📝 [Support][LIVE-3591] create client spec
LedgerHQ/platform-sdk pull request #1
Opened 2022-09-02 15:40 UTC by chabroA

Add the base of the Client API specification.

The main points of attention in this spec are the serialization and deserialization that the client needs to take care of and the error handling for the `completeExchange` method.

The rest is just implementing the RPC spec defined in `/spec/rpc/README.md`

2022-09-05 08:30 UTC, Justkant requested changes

2022-09-05 08:30 UTC, Justkant commented on spec/client/README.md
> +Similarly, the response received from the Server, formated as [`RawTransaction`]() and [`RawAccount`]() should be deserialized before being returned to the user of the Client (i.e: the Application in
```suggestion
Similarly, the response received from the Server, formatted as [`RawTransaction`]() and [`RawAccount`]() should be deserialized before being returned to the user of the Client (i.e: the Application integrating said client).
```

2022-09-05 15:10 UTC, chabroA commented on spec/client/README.md
> +Similarly, the response received from the Server, formated as [`RawTransaction`]() and [`RawAccount`]() should be deserialized before being returned to the user of the Client (i.e: the Application in
Done 👍

2022-09-06 10:58 UTC, Justkant approved these changes

2022-09-06 13:04 UTC, merged